### ISSUE TITLE
Having ".exe" as output confuses Wine on Linux

### ISSUE THREAD

**Issue by JobLeonard** [fsantanna/ceu-sdl#3]
Programs run fine run from the command line, but double-clicking on anything that ends with .exe results in Wine trying to run it, without success obviously.

Maybe it should have ".out" as the extension when compiling on Linux instead?

**Comment by fsantanna** [comment]
Ok.
(".exe" is confusing for Linux anyway)

**Comment by JobLeonard** [comment]
This edit to the makefile is the only thing that has to change, right?

Plus a minor edit to the documentation here:
http://www.ceu-lang.org/wiki/index.php?title=SDL

**Comment by fsantanna** [comment]
Not an issue in the new version.
