### ISSUE TITLE
Double free error happens when timeout trail terminates

### ISSUE THREAD

**Issue by calmattoso** [fsantanna/ceu-sdl#6]
When the timeout trail terminates, after `10s`, the program crashes due to the following error: ``*** Error in `./double_free': double free or corruption (!prev): 0x0000000001e48310 ***``

Code to reproduce the error:
```c
#include <c.ceu>
#include <sdl/sdl.ceu>

par/or do
    var int i;
    loop i do
        await 1us;
    end
with
    await 10s;
end

escape 0;
```
_Note: I was unable to reproduce this error in `ceu-libuv`._

**Comment by calmattoso** [comment]
_Note: I was unable to reproduce this error in `ceu-libuv`._

**Comment by fsantanna** [comment]
Can't reproduce here.
Does the `1us` and `10s` matter? (i.e., would `1ms` and `1s` also crash?)

**Comment by calmattoso** [comment]
Here `1ms` and `1s` immediately crashes. I made sure to update to the latest version of Céu (on branch `master`) and can still observe the issue. I've tested the following pairs:
- `100ms` and `1s`: works
- `50ms` and `1s`: works
- `5ms` and `1s`: fails
- `1ms` and `1s`: fails
- `1us` and `1s`: fails

Below are the compilation arguments I'm using, in case it helps:

```
ceu --pre --pre-args="-I/home/carlos/ceu/include -I/home/carlos/ceu-sdl/include -DDEBUG -Ddouble_free_test" \
          --pre-input=src/double_free.ceu \
    --ceu --ceu-features-lua=true --ceu-features-thread=true \
          --ceu-err-unused=pass --ceu-err-uninitialized=pass \
    --env --env-types=/home/carlos/ceu/env/types.h \
          --env-threads=/home/carlos/ceu/env/threads.h \
          --env-main=/home/carlos/ceu/env/main.c \
    --cc  --cc-args="-Isrc/ -lrabbitmq -llua5.3 -lpthread -lm -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lSDL2_gfx" \
          --cc-output=double_free
```
